# Generated by Django 3.1.6 on 2021-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='携帯電話番号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
    ]
